###
//getAllReviews
GET localhost:8083/reviews

###
//GetReviewById
GET localhost:8083/reviews/1

###
//CreateReview
POST localhost:8083/reviews
Content-Type: application/json

{
  "title": "Review Title",
  "message": "Review Message",
  "rating": 5.00,
  "companyId": 1
}

###
//UpdateReviewById
PUT http://localhost:8083/reviews/1
Content-Type: application/json

{
  "title": "Updated Review Title",
  "message": "Updated Review Message",
  "rating": 7.00,
  "companyId": 1
}

###
//DeleteReviewById
DELETE http://localhost:8083/reviews/1

###