apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-service
  labels:
    app: job-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: job-service
  template:
    metadata:
      name: job-service
      labels:
        app: job-service
    spec:
      containers:
        - name: job-service
          image: markbedoya/job-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
      restartPolicy: Always
      