###
//getAllCompanies
GET localhost:8081/companies

###
//GetCompanyById
GET localhost:8081/companies/1

###
//CreateCompany
POST http://localhost:8081/companies
Content-Type: application/json

{
  "name": "CompanyName",
  "description": "CompanyDescription"
}

###
//UpdateCompanyById
PUT http://localhost:8081/companies/1
Content-Type: application/json

{
  "name": "CompanyName Updated",
  "description": "CompanyDescription Updated"
}

###
//DeleteCompanyById
DELETE http://localhost:8081/companies/1

###