###
//getAllJobs
GET localhost:8082/jobs

###
//GetJobById
GET localhost:8082/jobs/1

###
//CreateJob
POST localhost:8082/jobs
Content-Type: application/json

{
  "title": "Title",
  "description": "Description",
  "minSalary": "30000",
  "maxSalary": "40000",
  "location": "Location",
  "test" : "test",
  "companyId" : 1
}

###
//UpdateJobById
PUT http://localhost:8082/jobs/1
Content-Type: application/json

{
  "title": "Title-Updated",
  "description": "Description-Updated",
  "minSalary": "50000",
  "maxSalary": "60000",
  "location": "Location-Updated"
}

###
//DeleteJobById
DELETE http://localhost:8082/jobs/1

###