apiVersion: apps/v1
kind: Deployment
metadata:
  name: company-service
  labels:
    app: 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: company-service
  template:
    metadata:
      name: company-service
      labels:
        app: company-service
    spec:
      containers:
        - name: company-service
          image: markbedoya/company-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
      restartPolicy: Always
      